In [11]:
teste = (3,2,3)

In [3]:
teste

(2, 3)

In [12]:
a, *b = teste

In [15]:
a, b

(3, [2, 3])

In [16]:
import numpy as np

In [20]:
teste_2 = (2,3)

In [23]:
*teste_2

SyntaxError: can't use starred expression here (4084876023.py, line 1)

In [25]:
arr = np.random.rand(2,3)
arr

array([[0.35728993, 0.45709702, 0.41557504],
       [0.4145872 , 0.29127433, 0.64185497]])

In [30]:
a = [1,1]
b = [True, False]

In [31]:
np.logical_xor(a,b)

array([False,  True])

In [36]:
arr = np.random.normal(0,2,size=(10,2))
arr

array([[-1.6682847 ,  0.19310339],
       [-3.78344373,  1.85120206],
       [-0.45522427,  3.52889083],
       [ 1.06163778, -1.91136025],
       [ 1.509531  ,  1.86673538],
       [-2.12935287,  1.07025403],
       [-0.36965417,  0.95138076],
       [-0.4801792 , -2.30971422],
       [ 1.38231965, -1.22015375],
       [ 0.74909948,  0.72411208]])

In [37]:
rng = np.random.default_rng()

In [57]:
idx_arr = np.arange(arr.shape[0])
idx_arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
teste = rng.choice(idx_arr, size=(5,2), replace=False, shuffle=True)

In [73]:
teste

array([[4, 3],
       [0, 1],
       [2, 6],
       [9, 8],
       [5, 7]])

In [61]:
arr.shape

(10, 2)

In [70]:
arr.reshape(5,2,2)

array([[[-1.6682847 ,  0.19310339],
        [-3.78344373,  1.85120206]],

       [[-0.45522427,  3.52889083],
        [ 1.06163778, -1.91136025]],

       [[ 1.509531  ,  1.86673538],
        [-2.12935287,  1.07025403]],

       [[-0.36965417,  0.95138076],
        [-0.4801792 , -2.30971422]],

       [[ 1.38231965, -1.22015375],
        [ 0.74909948,  0.72411208]]])