In [11]:
teste = (3,2,3)

In [3]:
teste

(2, 3)

In [12]:
a, *b = teste

In [15]:
a, b

(3, [2, 3])

In [1]:
import numpy as np

In [20]:
teste_2 = (2,3)

In [23]:
*teste_2

SyntaxError: can't use starred expression here (4084876023.py, line 1)

In [25]:
arr = np.random.rand(2,3)
arr

array([[0.35728993, 0.45709702, 0.41557504],
       [0.4145872 , 0.29127433, 0.64185497]])

In [30]:
a = [1,1]
b = [True, False]

In [31]:
np.logical_xor(a,b)

array([False,  True])

In [62]:
arr = np.random.normal(0,2,size=(10,2))
arr

array([[-0.4575722 , -1.12254709],
       [ 0.44565884,  2.32548575],
       [ 3.41664956,  0.18199845],
       [ 0.29860627, -2.03874405],
       [ 0.09508109,  0.77985918],
       [ 0.4785953 ,  1.23471241],
       [ 0.22128184, -1.30992124],
       [ 1.63347763,  0.300525  ],
       [-0.73401766,  1.92046066],
       [ 2.29701012,  0.13172514]])

In [63]:
fitness = np.random.randint(low=0, high=100, size=(10,1))
fitness

array([[44],
       [71],
       [76],
       [75],
       [ 1],
       [ 3],
       [89],
       [17],
       [47],
       [60]])

In [94]:
concat = np.concatenate((arr,fitness),axis=1)

In [103]:
concat

array([[ 2.65419616,  3.58173829, 65.        ],
       [-0.24388939,  3.27790281, 71.        ],
       [ 2.68858654,  0.95980325, 98.        ],
       [ 1.56859785, -3.80839918, 35.        ],
       [ 2.8571152 ,  0.46395347, 11.        ],
       [ 3.44275785, -0.15422168,  6.        ],
       [-0.16879847,  1.25740571, 24.        ],
       [-0.7445307 , -0.95546721, 67.        ],
       [-2.65607562,  0.7451109 , 65.        ],
       [ 0.60696424,  1.26131387,  7.        ]])

In [245]:
concat_2 = rng.choice(concat, size=(5,2), replace=False, shuffle=True)
concat_2

array([[[-0.7445307 , -0.95546721, 67.        ],
        [ 2.65419616,  3.58173829, 65.        ]],

       [[ 2.8571152 ,  0.46395347, 11.        ],
        [ 3.44275785, -0.15422168,  6.        ]],

       [[ 1.56859785, -3.80839918, 35.        ],
        [ 0.60696424,  1.26131387,  7.        ]],

       [[-0.16879847,  1.25740571, 24.        ],
        [ 2.68858654,  0.95980325, 98.        ]],

       [[-0.24388939,  3.27790281, 71.        ],
        [-2.65607562,  0.7451109 , 65.        ]]])

In [260]:
concat_2[0]

array([[-0.7445307 , -0.95546721, 67.        ],
       [ 2.65419616,  3.58173829, 65.        ]])

In [246]:
a, b = concat_2[:,:,:2], concat_2[:,:,2]
a, b

(array([[[-0.7445307 , -0.95546721],
         [ 2.65419616,  3.58173829]],
 
        [[ 2.8571152 ,  0.46395347],
         [ 3.44275785, -0.15422168]],
 
        [[ 1.56859785, -3.80839918],
         [ 0.60696424,  1.26131387]],
 
        [[-0.16879847,  1.25740571],
         [ 2.68858654,  0.95980325]],
 
        [[-0.24388939,  3.27790281],
         [-2.65607562,  0.7451109 ]]]),
 array([[67., 65.],
        [11.,  6.],
        [35.,  7.],
        [24., 98.],
        [71., 65.]]))

In [247]:
selected_pop = []
for i in range(len(a)):
    if b[i][0] > b[i][1]:
        selected_pop.append(a[i][0])
    elif b[i][0] < b[i][1]:
        selected_pop.append(a[i][1])
    else:
        idx = np.random.binomial(n=1, p=0.5)
        selected_pop.append(a[i][idx])
selected_pop = np.array(selected_pop)

In [84]:
k = 2
rng = np.random.default_rng()

def select(population, fitness):
    population_fitness = np.concatenate((population,fitness),axis=1)
    counter = population.shape[0]/k
    mating_pool = []
    while counter != 0:
        tournament_groups = rng.choice(population_fitness, size=(int(population.shape[0]/k), k), replace=False, shuffle=True)
        mating_pool.append(tournament_groups)
        counter-=counter
    mating_pool = np.array(mating_pool).squeeze(axis=0)
    selected_mating_pool = []
    for group in mating_pool:
        best_candidate_idx = 0
        best_candidates = []
        best_candidates.append(group[0])
        for i in range(1,k):
            if group[i][2] > group[best_candidate_idx][2]:
                best_candidates.clear()
                best_candidate_idx = i
                best_candidates.append(group[i])
            elif group[i][2] == group[best_candidate_idx][2]:
                best_candidates.append(group[i][2])
        selected_mating_pool.append(rng.choice(best_candidates, size=1, replace=False, shuffle=True))
    return mating_pool, np.array(selected_mating_pool).squeeze(axis=1)[:,:-1]

In [85]:
mating_pool, selected_mating_pool = select(arr, fitness)

In [86]:
mating_pool

array([[[ 0.4785953 ,  1.23471241,  3.        ],
        [ 0.29860627, -2.03874405, 75.        ]],

       [[ 2.29701012,  0.13172514, 60.        ],
        [ 1.63347763,  0.300525  , 17.        ]],

       [[-0.73401766,  1.92046066, 47.        ],
        [ 3.41664956,  0.18199845, 76.        ]],

       [[ 0.09508109,  0.77985918,  1.        ],
        [-0.4575722 , -1.12254709, 44.        ]],

       [[ 0.44565884,  2.32548575, 71.        ],
        [ 0.22128184, -1.30992124, 89.        ]]])

In [88]:
selected_mating_pool

array([[ 0.29860627, -2.03874405],
       [ 2.29701012,  0.13172514],
       [ 3.41664956,  0.18199845],
       [-0.4575722 , -1.12254709],
       [ 0.22128184, -1.30992124]])

In [25]:
teste[0][1]

array([ 2.27983266, -1.26750968, 17.        ])

In [221]:
a[:,0]

array([[-0.7445307 , -0.95546721],
       [-0.16879847,  1.25740571],
       [ 3.44275785, -0.15422168],
       [ 2.8571152 ,  0.46395347],
       [ 0.60696424,  1.26131387]])

In [205]:
a[:,b_idx,:]

array([[[[-0.7445307 , -0.95546721]],

        [[ 1.56859785, -3.80839918]],

        [[ 1.56859785, -3.80839918]],

        [[ 1.56859785, -3.80839918]],

        [[ 1.56859785, -3.80839918]]],


       [[[-0.16879847,  1.25740571]],

        [[ 2.65419616,  3.58173829]],

        [[ 2.65419616,  3.58173829]],

        [[ 2.65419616,  3.58173829]],

        [[ 2.65419616,  3.58173829]]],


       [[[ 3.44275785, -0.15422168]],

        [[-0.24388939,  3.27790281]],

        [[-0.24388939,  3.27790281]],

        [[-0.24388939,  3.27790281]],

        [[-0.24388939,  3.27790281]]],


       [[[ 2.8571152 ,  0.46395347]],

        [[ 2.68858654,  0.95980325]],

        [[ 2.68858654,  0.95980325]],

        [[ 2.68858654,  0.95980325]],

        [[ 2.68858654,  0.95980325]]],


       [[[ 0.60696424,  1.26131387]],

        [[-2.65607562,  0.7451109 ]],

        [[-2.65607562,  0.7451109 ]],

        [[-2.65607562,  0.7451109 ]],

        [[-2.65607562,  0.7451109 ]]]])

In [ ]:
arr, fitness

(array([[ 2.65419616,  3.58173829],
        [-0.24388939,  3.27790281],
        [ 2.68858654,  0.95980325],
        [ 1.56859785, -3.80839918],
        [ 2.8571152 ,  0.46395347],
        [ 3.44275785, -0.15422168],
        [-0.16879847,  1.25740571],
        [-0.7445307 , -0.95546721],
        [-2.65607562,  0.7451109 ],
        [ 0.60696424,  1.26131387]]),
 array([[65],
        [71],
        [98],
        [35],
        [11],
        [ 6],
        [24],
        [67],
        [65],
        [ 7]]))

In [37]:
rng = np.random.default_rng()

In [57]:
idx_arr = np.arange(arr.shape[0])
idx_arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
teste = rng.choice(idx_arr, size=(5,2), replace=False, shuffle=True)