In [63]:
import numpy as np

In [74]:
X = np.random.uniform(-5,5,(5,2))

In [106]:
mask = np.random.uniform(low=0, high=1, size=(X.shape)) < 0.9
mask

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True]])

In [120]:
j_idx = np.random.randint(low=0, high=X.shape[1], size=X.shape[0])
j_idx

array([0, 1, 1, 0, 1])

In [121]:
mask[np.arange(X.shape[0]), j_idx]

array([False,  True,  True, False,  True])

In [105]:
mask

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [126]:
pop_size = 10

In [72]:
differences = 2

In [73]:
differences in [1,2]

True

In [105]:
r1_idx = np.random.randint(0, pop_size, size=pop_size)
r1_idx

i_idx = np.arange(pop_size)

r1_idx, i_idx

(array([1, 1, 4, 4, 4, 7, 0, 1, 5, 2]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [115]:
while np.any(r1_idx == i_idx):
    mask = (r1_idx == i_idx)
    r1_idx[mask] = np.random.randint(0,pop_size,size=np.sum(mask))

In [116]:
r1_idx, i_idx

(array([1, 2, 4, 4, 0, 7, 0, 1, 5, 2]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [117]:
r1_idx == i_idx

array([False, False, False, False, False, False, False, False, False,
       False])

np.int64(2)

In [82]:
r1_idx = np.where(r1_idx == i_idx, (r1_idx + 1) % pop_size, r1_idx)
r2_idx = np.where((r2_idx == i_idx) | (r2_idx == r1_idx), (r2_idx + 2) % pop_size, r2_idx)
r3_idx = np.where((r3_idx == i_idx) | (r3_idx == r1_idx) | (r3_idx == r2_idx), (r3_idx + 3) % pop_size, r3_idx)

r1_idx, r2_idx, r3_idx

(array([7, 9, 3, 8, 5, 6, 1, 3, 0, 5]),
 array([5, 8, 5, 6, 7, 4, 2, 0, 9, 1]),
 array([8, 6, 4, 6, 2, 9, 4, 5, 7, 0]))

In [127]:
X = np.random.uniform(low=-5, high=5, size=(pop_size,2))
X

array([[ 2.2750086 ,  1.12135335],
       [-4.0118864 ,  2.58707144],
       [ 2.16569275,  1.4950187 ],
       [ 3.52521134, -3.02068603],
       [ 2.3013794 ,  0.81949272],
       [-2.52996326,  4.62958839],
       [-4.93806231, -4.59331175],
       [-0.64130843, -4.71476501],
       [-4.13582631, -4.78246442],
       [ 0.01532886, -1.32763099]])

In [84]:
X[r1_idx]

array([[-2.331705  , -3.96767406],
       [-3.36914929,  1.46320011],
       [-1.29940032, -2.16940619],
       [-0.34350082,  1.19470662],
       [ 1.75203009, -3.12213224],
       [-2.82927005,  4.55495734],
       [ 0.82238429, -0.92040809],
       [-1.29940032, -2.16940619],
       [ 4.25805331,  0.80244898],
       [ 1.75203009, -3.12213224]])

In [85]:
X[r2_idx]

array([[ 1.75203009, -3.12213224],
       [-0.34350082,  1.19470662],
       [ 1.75203009, -3.12213224],
       [-2.82927005,  4.55495734],
       [-2.331705  , -3.96767406],
       [ 3.8039411 , -1.76309612],
       [ 1.99345758,  1.84281628],
       [ 4.25805331,  0.80244898],
       [-3.36914929,  1.46320011],
       [ 0.82238429, -0.92040809]])

In [63]:
np.where(mask, new_X, p_best)

array([[-3,  3],
       [ 2, 10],
       [ 2,  6]])

In [132]:
X.shape, bounds.shape

((10, 2), (2, 2))

In [133]:
X

array([[ 2.2750086 ,  1.12135335],
       [-4.0118864 ,  2.58707144],
       [ 2.16569275,  1.4950187 ],
       [ 3.52521134, -3.02068603],
       [ 2.3013794 ,  0.81949272],
       [-2.52996326,  4.62958839],
       [-4.93806231, -4.59331175],
       [-0.64130843, -4.71476501],
       [-4.13582631, -4.78246442],
       [ 0.01532886, -1.32763099]])

In [135]:
np.clip(X,a_min=bounds[:,0],a_max=bounds[:,-1])

array([[ 2.2750086 ,  1.12135335],
       [-3.        ,  1.5       ],
       [ 2.16569275,  1.4950187 ],
       [ 3.        , -3.02068603],
       [ 2.3013794 ,  0.81949272],
       [-2.52996326,  1.5       ],
       [-3.        , -4.        ],
       [-0.64130843, -4.        ],
       [-3.        , -4.        ],
       [ 0.01532886, -1.32763099]])

In [33]:
bounds[:,0][:,np.newaxis]

array([[-5],
       [ 1],
       [ 2]])

In [134]:
bounds = np.array([[-3,3],[-4,1.5]])
bounds

array([[-3. ,  3. ],
       [-4. ,  1.5]])

In [129]:
bounds.shape

(3, 2)

In [124]:
bounds[:,1]

array([10, -2,  5])

In [60]:
teste = np.random.uniform(low=bounds[:,0], high=bounds[:,1], size=(10,3))
teste

array([[ 5.51871896, -2.97949062, -3.1189578 ],
       [ 4.85631666, -2.09622039, -0.75589077],
       [ 6.37550058, -2.21885266, -1.2924041 ],
       [ 7.13610152, -3.87990967, -0.22283689],
       [ 0.72985806, -3.88840762,  3.28960508],
       [ 8.11105283, -3.74928537, -3.41999833],
       [ 4.16445453, -3.71742251, -2.83068186],
       [ 2.39382675, -3.20428479,  3.99128314],
       [ 9.68938887, -2.39543602, -0.73611822],
       [ 1.62467664, -2.48482207,  3.68033824]])

In [61]:
teste[:,:-1]

array([[ 5.51871896, -2.97949062],
       [ 4.85631666, -2.09622039],
       [ 6.37550058, -2.21885266],
       [ 7.13610152, -3.87990967],
       [ 0.72985806, -3.88840762],
       [ 8.11105283, -3.74928537],
       [ 4.16445453, -3.71742251],
       [ 2.39382675, -3.20428479],
       [ 9.68938887, -2.39543602],
       [ 1.62467664, -2.48482207]])

In [62]:
teste[:,1:]

array([[-2.97949062, -3.1189578 ],
       [-2.09622039, -0.75589077],
       [-2.21885266, -1.2924041 ],
       [-3.87990967, -0.22283689],
       [-3.88840762,  3.28960508],
       [-3.74928537, -3.41999833],
       [-3.71742251, -2.83068186],
       [-3.20428479,  3.99128314],
       [-2.39543602, -0.73611822],
       [-2.48482207,  3.68033824]])

In [20]:
teste_2 = (2,3)

In [23]:
*teste_2

SyntaxError: can't use starred expression here (4084876023.py, line 1)

In [25]:
arr = np.random.rand(2,3)
arr

array([[0.35728993, 0.45709702, 0.41557504],
       [0.4145872 , 0.29127433, 0.64185497]])

In [30]:
a = [1,1]
b = [True, False]

In [31]:
np.logical_xor(a,b)

array([False,  True])

In [62]:
arr = np.random.normal(0,2,size=(10,2))
arr

array([[-0.4575722 , -1.12254709],
       [ 0.44565884,  2.32548575],
       [ 3.41664956,  0.18199845],
       [ 0.29860627, -2.03874405],
       [ 0.09508109,  0.77985918],
       [ 0.4785953 ,  1.23471241],
       [ 0.22128184, -1.30992124],
       [ 1.63347763,  0.300525  ],
       [-0.73401766,  1.92046066],
       [ 2.29701012,  0.13172514]])

In [63]:
fitness = np.random.randint(low=0, high=100, size=(10,1))
fitness

array([[44],
       [71],
       [76],
       [75],
       [ 1],
       [ 3],
       [89],
       [17],
       [47],
       [60]])

In [94]:
concat = np.concatenate((arr,fitness),axis=1)

In [103]:
concat

array([[ 2.65419616,  3.58173829, 65.        ],
       [-0.24388939,  3.27790281, 71.        ],
       [ 2.68858654,  0.95980325, 98.        ],
       [ 1.56859785, -3.80839918, 35.        ],
       [ 2.8571152 ,  0.46395347, 11.        ],
       [ 3.44275785, -0.15422168,  6.        ],
       [-0.16879847,  1.25740571, 24.        ],
       [-0.7445307 , -0.95546721, 67.        ],
       [-2.65607562,  0.7451109 , 65.        ],
       [ 0.60696424,  1.26131387,  7.        ]])

In [245]:
concat_2 = rng.choice(concat, size=(5,2), replace=False, shuffle=True)
concat_2

array([[[-0.7445307 , -0.95546721, 67.        ],
        [ 2.65419616,  3.58173829, 65.        ]],

       [[ 2.8571152 ,  0.46395347, 11.        ],
        [ 3.44275785, -0.15422168,  6.        ]],

       [[ 1.56859785, -3.80839918, 35.        ],
        [ 0.60696424,  1.26131387,  7.        ]],

       [[-0.16879847,  1.25740571, 24.        ],
        [ 2.68858654,  0.95980325, 98.        ]],

       [[-0.24388939,  3.27790281, 71.        ],
        [-2.65607562,  0.7451109 , 65.        ]]])

In [260]:
concat_2[0]

array([[-0.7445307 , -0.95546721, 67.        ],
       [ 2.65419616,  3.58173829, 65.        ]])

In [246]:
a, b = concat_2[:,:,:2], concat_2[:,:,2]
a, b

(array([[[-0.7445307 , -0.95546721],
         [ 2.65419616,  3.58173829]],
 
        [[ 2.8571152 ,  0.46395347],
         [ 3.44275785, -0.15422168]],
 
        [[ 1.56859785, -3.80839918],
         [ 0.60696424,  1.26131387]],
 
        [[-0.16879847,  1.25740571],
         [ 2.68858654,  0.95980325]],
 
        [[-0.24388939,  3.27790281],
         [-2.65607562,  0.7451109 ]]]),
 array([[67., 65.],
        [11.,  6.],
        [35.,  7.],
        [24., 98.],
        [71., 65.]]))

In [247]:
selected_pop = []
for i in range(len(a)):
    if b[i][0] > b[i][1]:
        selected_pop.append(a[i][0])
    elif b[i][0] < b[i][1]:
        selected_pop.append(a[i][1])
    else:
        idx = np.random.binomial(n=1, p=0.5)
        selected_pop.append(a[i][idx])
selected_pop = np.array(selected_pop)

In [84]:
k = 2
rng = np.random.default_rng()

def select(population, fitness):
    population_fitness = np.concatenate((population,fitness),axis=1)
    counter = population.shape[0]/k
    mating_pool = []
    while counter != 0:
        tournament_groups = rng.choice(population_fitness, size=(int(population.shape[0]/k), k), replace=False, shuffle=True)
        mating_pool.append(tournament_groups)
        counter-=counter
    mating_pool = np.array(mating_pool).squeeze(axis=0)
    selected_mating_pool = []
    for group in mating_pool:
        best_candidate_idx = 0
        best_candidates = []
        best_candidates.append(group[0])
        for i in range(1,k):
            if group[i][2] > group[best_candidate_idx][2]:
                best_candidates.clear()
                best_candidate_idx = i
                best_candidates.append(group[i])
            elif group[i][2] == group[best_candidate_idx][2]:
                best_candidates.append(group[i][2])
        selected_mating_pool.append(rng.choice(best_candidates, size=1, replace=False, shuffle=True))
    return mating_pool, np.array(selected_mating_pool).squeeze(axis=1)[:,:-1]

In [85]:
mating_pool, selected_mating_pool = select(arr, fitness)

In [86]:
mating_pool

array([[[ 0.4785953 ,  1.23471241,  3.        ],
        [ 0.29860627, -2.03874405, 75.        ]],

       [[ 2.29701012,  0.13172514, 60.        ],
        [ 1.63347763,  0.300525  , 17.        ]],

       [[-0.73401766,  1.92046066, 47.        ],
        [ 3.41664956,  0.18199845, 76.        ]],

       [[ 0.09508109,  0.77985918,  1.        ],
        [-0.4575722 , -1.12254709, 44.        ]],

       [[ 0.44565884,  2.32548575, 71.        ],
        [ 0.22128184, -1.30992124, 89.        ]]])

In [88]:
selected_mating_pool

array([[ 0.29860627, -2.03874405],
       [ 2.29701012,  0.13172514],
       [ 3.41664956,  0.18199845],
       [-0.4575722 , -1.12254709],
       [ 0.22128184, -1.30992124]])

In [25]:
teste[0][1]

array([ 2.27983266, -1.26750968, 17.        ])

In [221]:
a[:,0]

array([[-0.7445307 , -0.95546721],
       [-0.16879847,  1.25740571],
       [ 3.44275785, -0.15422168],
       [ 2.8571152 ,  0.46395347],
       [ 0.60696424,  1.26131387]])

In [205]:
a[:,b_idx,:]

array([[[[-0.7445307 , -0.95546721]],

        [[ 1.56859785, -3.80839918]],

        [[ 1.56859785, -3.80839918]],

        [[ 1.56859785, -3.80839918]],

        [[ 1.56859785, -3.80839918]]],


       [[[-0.16879847,  1.25740571]],

        [[ 2.65419616,  3.58173829]],

        [[ 2.65419616,  3.58173829]],

        [[ 2.65419616,  3.58173829]],

        [[ 2.65419616,  3.58173829]]],


       [[[ 3.44275785, -0.15422168]],

        [[-0.24388939,  3.27790281]],

        [[-0.24388939,  3.27790281]],

        [[-0.24388939,  3.27790281]],

        [[-0.24388939,  3.27790281]]],


       [[[ 2.8571152 ,  0.46395347]],

        [[ 2.68858654,  0.95980325]],

        [[ 2.68858654,  0.95980325]],

        [[ 2.68858654,  0.95980325]],

        [[ 2.68858654,  0.95980325]]],


       [[[ 0.60696424,  1.26131387]],

        [[-2.65607562,  0.7451109 ]],

        [[-2.65607562,  0.7451109 ]],

        [[-2.65607562,  0.7451109 ]],

        [[-2.65607562,  0.7451109 ]]]])

In [ ]:
arr, fitness

(array([[ 2.65419616,  3.58173829],
        [-0.24388939,  3.27790281],
        [ 2.68858654,  0.95980325],
        [ 1.56859785, -3.80839918],
        [ 2.8571152 ,  0.46395347],
        [ 3.44275785, -0.15422168],
        [-0.16879847,  1.25740571],
        [-0.7445307 , -0.95546721],
        [-2.65607562,  0.7451109 ],
        [ 0.60696424,  1.26131387]]),
 array([[65],
        [71],
        [98],
        [35],
        [11],
        [ 6],
        [24],
        [67],
        [65],
        [ 7]]))

In [37]:
rng = np.random.default_rng()

In [57]:
idx_arr = np.arange(arr.shape[0])
idx_arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
teste = rng.choice(idx_arr, size=(5,2), replace=False, shuffle=True)